package com.webrpg.app.model.derived;

public class DataList {

    public enum RaceType {
        ELF, HUMAN, DWARF, GNOME, GOBLIN, ORC
    }

    public enum AbilityType {
        STRENGTH, CONSTITUTION, DEXTERITY, INTELLIGENCE, WISDOM, CHARISMA
    }

    public enum SkillType
    {
        ACROBATICS,ARCANA,ATHLETICS,CRAFTING,DECEPTION,DIPLOMACY,INTIMIDATION,MEDICINE,NATURE,OCCULTISM,PERFORMANCE,RELIGION,
        SOCIETY,STEALTH,SURVIVAL,THIEVERY,LORE,LORE_ARCANA,LORE_DUNGEONEERING,
        LORE_LOCAL,LORE_NATURE,LORE_RELIGION,LORE_PLANAR,LORE_GEOLOGY
    }

    public enum FeatType {
        ACTOR,ALERT,ATHLETE,BARBED_HIDE,BOUNTIFUL_LUCK,CHARGER,CRITTER_FRIEND,CROSSBOW_EXPERT,DEFENSIVE_DUELIST,DRAGON_FEAR,
        DRAGON_HIDE,DRAGON_WINGS,DROW_HIDE_MAGIC,DUAL_WIELDER,DUNGEON_DELVER,DURABLE,DWARF_RESILIENCE,DWARVEN_FORTITUDE,
        ELEMENTAL_ADEPT,ELVEN_ACCURACY,EVERYBODYS_FRIEND,FADE_AWAY,FEY_TELEPORTATION,FLAMES_OF_PHLEGETHOS,GRAPPLER
        ,GREAT_WEAPON_MASTER,GRUDGE_BEARER,HEALER,HEAVILY_ARMORED,HEAVY_ARMOR_MASTER,HUMAN_DETERMINATION
        ,INFERNAL_CONSTITUTION,INSPIRING_LEADER,KEEN_MIND,LIGHTLY_ARMORED,LINGUIST,LUCKY,MAGE_SLAYER,MAGIC_INITIATE,
        MARTIAL_ADEPT,MEDIUM_ARMOR_MASTER,MOBILE,MODERATELY_ARMORED,MOUNTED_COMBATANT,OBSERVANT,ORCISH_AGGRESSION,
        ORCISH_FURY,POLEARM_MASTER,PRODIGY,RESILIENT,RITUAL_CASTER,SAVAGE_ATTACKER,SECOND_CHANCE,SENTINEL,SHARPSHOOTER,
        SHIELD_MASTER,SKILLED,SKULKER,SPELL_SNIPER,SQUAT_NIMBLENESS,TAVERN_BRAWLER,TOUGH,WAR_CASTER,WEAPON_MASTER,WONDER_MAKER
    }
    public enum BigFiveType{
        OPENNESS,CONSCIENTIOUSNESS,EXTROVERSION,AGREEABLENESS,NEUROTICISM
    }
    public enum BigFiveSubType{
        ADVENTUROUSNESS,ARTISTIC_INTERESTS,EMOTIONALITY,IMAGINATION,INTELLECT,AUTHORITY_CHALLENGING,ACHIEVEMENT_STRIVING,
        CAUTIOUSNESS,DUTIFULNESS,ORDERLINESS,SELF_DISCIPLINE,SELF_EFFICACY,ACTIVITY_LEVEL,ASSERTIVENESS,CHEERFULNESS,
        EXCITEMENT_SEEKING,OUTGOING,GREGARIOUSNESS,ALTRUISM,COOPERATION,MODESTY,UNCOMPROMISING,SYMPATHY,TRUST,FIERY,
        PRONE_TO_WORRY,MELANCHOLY,IMMODERATION,SELF_CONSCIOUSNESS,SUSCEPTIBLE_TO_STRESS
    }
}
